[tool.black]
line-length = 120
# Black  normalize ' to " - setting to 1 will disable normalization
skip-string-normalization = 1


[tool.isort]
line_length = 120
use_parentheses = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
multi_line_output = 3
import_headings = {future="Special Imports ------------------------------------------------------------------------------------------------------", stdlib="Standard Library Imports ---------------------------------------------------------------------------------------------", thirdparty="Third Party Library Imports ------------------------------------------------------------------------------------------", firstparty="Local Application Imports --------------------------------------------------------------------------------------------", localfolder="Local Folder (Relative) Imports --------------------------------------------------------------------------------------"}
ensure_newline_before_comments = true
include_trailing_comma = true
split_on_trailing_comma = true
float_to_top = true
indented_import_headings = false
# Default Settings: Order imports by type, which is determined by case, in addition to alphabetically.
# These "types" are simply: CONSTANT_VARIABLE, CamelCaseClass, variable_or_function
# Force all imports to be sorted alphabetically within a section insteasd of by type first.
#force_alphabetical_sort_within_sections = true
# If enabled, isort will strip comments that exist within import lines. - doesn't seem to work so commented out
#ignore_comments = true
known_first_party = ['CarloCodes']
known_future_library = ['__future__', 'config']
